server:
  port: 9600

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/timeside;MODE=MYSQL
    testWhileIdle: true
    validationQuery: SELECT 1
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  queries:
    users-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
  thymeleaf:
    cache: false
---
spring:
  profiles: dev-mySQL
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timeside
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
